development:
  clients:
    default:
     uri: <%= ENV['MONGODB_HOSTS_DEV'] %>
     options:
       connect_timeout: 15
test:
  clients:
    default:
     uri: <%= ENV['MONGODB_HOSTS_TEST'] %>
     options:
       connect_timeout: 15
production:
  clients:
    default:
     uri: <%= ENV['MONGODB_URI'] %>
     options:
       connect_timeout: 15
